### PR TITLE
fix(bundler-vite): fix build failure when theme has no styles (fix #697)

### LINKED ISSUE #697: [Bug report] Running "npm run docs:dev" fails when using local theme
I created a basic Vuepress 2 website, using the code from the guide: https://v2.vuepress.vuejs.org/guide/getting-started.html. Everything works fine when using the default theme.

The issue occurred when I created a local theme. Running the dev command `npm run docs:dev` works fine, but when I run the build command `npm run docs:build` it fails, throwing the following message:
```
Rendering pages - failed
TypeError: Cannot read properties of undefined (reading 'fileName')
    at renderPageStyles (D:\vuepress\vuepress-docs\node_modules\@vuepress\bundler-vite\lib\build\renderPageStyles.js:7:122)
    at renderPage (D:\vuepress\vuepress-docs\node_modules\@vuepress\bundler-vite\lib\build\renderPage.js:43:88)
    at async D:\vuepress\vuepress-docs\node_modules\@vuepress\bundler-vite\lib\build\createBuild.js:46:13
    at async D:\vuepress\vuepress-docs\node_modules\@vuepress\utils\lib\withSpinner.js:12:24
    at async Object.build (D:\vuepress\vuepress-docs\node_modules\@vuepress\bundler-vite\lib\build\createBuild.js:30:5)
    at async D:\vuepress\vuepress-docs\node_modules\@vuepress\cli\lib\commands\build\createBuild.js:49:5
```
Repo [here](https://github.com/cezarmaftei/vuepress-local-theme).

### PR DESCRIPTION
**Pull request by Mister-Hope**

### CODE REVIEW

File: packages/@vuepress/bundler-vite/src/build/renderPage.ts [hunk 1]
```diff
@@ -73,7 +73,7 @@ export const renderPage = async ({
     // page styles
     .replace(
       '<!--vuepress-ssr-styles-->',
-      renderPageStyles({ app, outputCssAsset })
+      outputCssAsset ? renderPageStyles({ app, outputCssAsset }) : ''
```
Comment (meteorlxy) [inline packages/@vuepress/bundler-vite/src/build/renderPage.ts:76]: Could be better to handle inside `renderPageStyles` func

**Review by meteorlxy — CHANGES_REQUESTED** [review]

**Review by meteorlxy — APPROVED** [review]
